name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: \${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        architecture: [amd64, aarch64]
        graalvm_version: [latest, 21]
        exclude:
          - os: windows-latest
            architecture: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: \${{ matrix.graalvm_version }}

      - name: Run Maven package and verification
        run: mvn package verify
