# Gradle sometimes lags JDK LTS release support, at which point the JDK used
# to run the Gradle daemon has to be an older LTS, which is what this is testing.
# This will be replaced by the integration tests:
# pass -Dgradle.java.home to Maven or --gradle-java-home to the Python test driver
org.gradle.java.home={GRADLE_JAVA_HOME}
org.gradle.java.installations.fromEnv=JAVA_HOME
