name: Build Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  graalvm_version: '26-ea'

jobs:
  # This is done as one single separate step to work around rate limits for the API
  maven_bundle_url:
    runs-on: ubuntu-latest
    outputs:
      maven_bundle_url: ${{ steps.set_url.outputs.maven_bundle_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 21
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set Maven Bundle URL
        id: set_url
        run: echo "maven_bundle_url=$(./scripts/maven-bundle-url.sh | tail -n 1)" >> $GITHUB_OUTPUT
        shell: bash

  build:
    runs-on: ${{ matrix.os }}
    needs: maven_bundle_url
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 21
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set GRADLE_JAVA_HOME
        run: echo "GRADLE_JAVA_HOME=${{ steps.java21.outputs.path }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: ${{ env.graalvm_version }}

      - name: Setup Polyglot Maven bundle
        run: ./scripts/maven-bundle-setup.sh "${{ github.workspace }}/maven-resource-bundle" "${{ needs.maven_bundle_url.outputs.maven_bundle_url }}"
        shell: bash

      - name: Build project (skip tests)
        run: mvn --batch-mode -DskipTests -s settings.xml -Dgradle.java.home=$GRADLE_JAVA_HOME package verify
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}
          path: ./**/target/**

  integration:
    needs: [build, maven_bundle_url]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        #test_name: [ test_jbang_integration.py, test_maven_plugin.py, test_gradle_plugin.py ]
        test_name: [ test_maven_plugin.py ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set integration tests flags
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "TEST_FLAGS=--skip-long-running" >> $GITHUB_ENV
          else
            echo "TEST_FLAGS=" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}
          path: .

      - name: Setup Java 21
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set GRADLE_JAVA_HOME
        run: echo "GRADLE_JAVA_HOME=${{ steps.java21.outputs.path }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: ${{ env.graalvm_version }}

      - name: Setup Polyglot Maven bundle
        run: ./scripts/maven-bundle-setup.sh "${{ github.workspace }}/maven-resource-bundle" "${{ needs.maven_bundle_url.outputs.maven_bundle_url }}"
        shell: bash

      - name: Run Maven install
        run: mvn --batch-mode -s settings.xml -Dgradle.java.home=$GRADLE_JAVA_HOME -DskipTests install
        shell: bash

      - name: Install JBang (Linux/macOS)
        if: runner.os != 'Windows' && matrix.test_name == 'test_jbang_integration.py'
        run: |
          curl -Ls https://sh.jbang.dev | bash
          echo "$HOME/.jbang/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install JBang (Windows)
        if: runner.os == 'Windows' && matrix.test_name == 'test_jbang_integration.py'
        run: choco install jbang
        shell: pwsh

      - name: DEBUG PyPI access curl
        run: |
          curl -H "Accept: application/vnd.pypi.simple.v1+json" https://pypi.org/simple/termcolor/
        shell: bash

      - name: DEBUG PyPI access GraalPy
        run: |
          mvn -s settings.xml exec:java@graalpy-shell -Dexec.args="download.py"
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: DEBUG PyPI access CPython
        run: pip install termcolor==2.2

      - name: Run integration tests
        run: |
          mvn --batch-mode -s settings.xml -Dgradle.java.home=$GRADLE_JAVA_HOME exec:java@integration-tests -Dintegration.tests.args="${{ matrix.test_name }} $TEST_FLAGS"
        shell: bash
