name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '25-ea'

      - name: Setup Polyglot Maven bundle
        uses: ./.github/actions/setup-polyglot-mvn-repo

      - name: Run Maven package install
        run: mvn --batch-mode -s settings.xml package install

      - name: Run integration tests
        run: mvn --batch-mode -s settings.xml exec:java@integration-tests