name: Java Interface Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '25-ea'

      - name: Setup Polyglot Maven bundle
        uses: ./.github/actions/setup-polyglot-mvn-repo

      - name: Build javainterfacegen tool
        run: mvn --batch-mode -s settings.xml -DskipTests -pl javainterfacegen -am -Pnative package

      - name: Publish javainterfacegen tool
        uses: actions/upload-artifact@v4
        with:
          name: javainterfacegen
          path: |
            javainterfacegen/target/javainterfacegen