name: Unit Tests

on:
  workflow_run:
    workflows: ["Build Artifacts"]
    types:
      - completed

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - job_name: "unit"
            maven_args: "test"
            display: "All Unit Tests"
          - job_name: "isolate-integration"
            maven_args: >-
              -Pisolate -Dpolyglot.engine.AllowExperimentalOptions=true -Dpolyglot.engine.SpawnIsolate=true -Dpolyglot.engine.IsolateMode=external -Dtest=org.graalvm.python.embedding.test.integration.* test
            display: "Isolated Embedding Integration Unit Tests"

    name: ${{ matrix.display }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Extract build artifacts
        run: |
          tar -xzf all-targets.tgz

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '25-ea'

      - name: Setup Polyglot Maven bundle
        uses: ./.github/actions/setup-polyglot-mvn-repo

      - name: Run Maven tests
        run: mvn --batch-mode -s settings.xml ${{ matrix.maven_args }}
